spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:all-citizen;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: rootpwd

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2
