server:
  port: 8090
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/plain, text/css, text/javascript, application/javascript, application/json
  undertow:
    threads:
      worker: 64
      io: 4