server:
  port: 8090
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/plain, text/css, text/javascript, application/javascript, application/json
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.schema}
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: false
      hibernate.connection.provider_disables_autocommit: true
